"""
Ensemble script: Blends predictions from LightGBM, XGBoost, and CatBoost.
Mimics the VotingRegressor strategy from the reference notebook.
"""
import argparse
import sys
from pathlib import Path
import pandas as pd
import numpy as np

# Project setup
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.config import Config

def post_process_biomass(y_pred_df):
    """
    Physical consistency constraint: Green + Dead + Clover should equal Total (roughly).
    """
    ordered_cols = ["Dry_Green_g", "Dry_Clover_g", "Dry_Dead_g", "GDM_g", "Dry_Total_g"]
    Y = y_pred_df[ordered_cols].values.T
    C = np.array([[1, 1, 0, -1,  0], [0, 0, 1,  1, -1]])
    P = np.eye(5) - C.T @ np.linalg.inv(C @ C.T) @ C
    Y_reconciled = (P @ Y).T.clip(min=0)
    df_out = y_pred_df.copy()
    df_out[ordered_cols] = Y_reconciled
    return df_out

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--weights", type=float, nargs=3, default=[0.34, 0.33, 0.33], 
                        help="Weights for LGBM, XGB, CatBoost (must sum to 1)")
    args = parser.parse_args()
    
    # Paths
    sub_dir = Path("submissions")
    output_path = sub_dir / "submission_ensemble.csv"
    
    # File names (Generated by previous scripts)
    files = {
        "lgbm": sub_dir / "submission_lgbm.csv",
        "xgb":  sub_dir / "submission_xgb.csv",
        "cat":  sub_dir / "submission_cat.csv"
    }
    
    # Load Submissions
    dfs = {}
    for model, path in files.items():
        if not path.exists():
            raise FileNotFoundError(f"Missing submission file: {path}. Please run prediction for {model} first.")
        
        df = pd.read_csv(path)
        # Ensure sorting matches
        df = df.sort_values("sample_id").reset_index(drop=True)
        dfs[model] = df
        print(f"Loaded {model}: {len(df)} rows")

    # Check consistency
    base_ids = dfs["lgbm"]["sample_id"]
    if not (dfs["xgb"]["sample_id"].equals(base_ids) and dfs["cat"]["sample_id"].equals(base_ids)):
        raise ValueError("Sample IDs do not match across submission files!")

    # Reference weights (LGBM, XGB, Cat)
    # The reference notebook uses VotingRegressor which roughly averages them.
    # We can slightly tweak weights based on CV scores if needed.
    w_lgbm, w_xgb, w_cat = args.weights
    print(f"Ensembling with weights -> LGBM: {w_lgbm}, XGB: {w_xgb}, Cat: {w_cat}")

    # Weighted Average
    # We need to extract the target values. 
    # Since submission files are in "long" format (sample_id, target), we need to pivot or iterate carefully.
    # Actually, the submission format is just 'sample_id', 'target'.
    
    # Let's merge them to be safe
    merged = dfs["lgbm"].copy().rename(columns={"target": "pred_lgbm"})
    merged["pred_xgb"] = dfs["xgb"]["target"]
    merged["pred_cat"] = dfs["cat"]["target"]
    
    # Calculate Ensemble Prediction
    merged["target"] = (
        merged["pred_lgbm"] * w_lgbm +
        merged["pred_xgb"]  * w_xgb +
        merged["pred_cat"]  * w_cat
    )
    
    # Final Submission
    final_sub = merged[["sample_id", "target"]]
    
    # Save
    sub_dir.mkdir(exist_ok=True)
    final_sub.to_csv(output_path, index=False)
    print(f"Ensemble submission saved to {output_path}")
    print(final_sub.head())

if __name__ == "__main__":
    main()